### ISSUE TITLE
Kein TinyMCE in EditorFormular

### ISSUE THREAD

**Issue by swinde** [mindbird/contao-calendar-editor#1]
Hallo mit dem neuen Repo wird der TinyMCE im Editorformular nicht geladen.

Im Backendmodul Event-Editor steht in den Template-Einstellungen für den Richtext Editor Unbekannte Option: tinyFrontendMore.

VG Steffen Winde

**Comment by swinde** [comment]
Im Frontend wird folgende Meldung ausgegeben:
`Cannot find rich text editor configuration file "/srv/www/xxx/public/vendor/danielgausi/contao-calendareditor-bundle/src/Resources/contao/tinyMCE/tinyFrontendMore.php"`

**Comment by Wusch** [comment]
Die Version 4.3.3 sollte das beheben.

**Comment by swinde** [comment]
Funktioniert! Danke!
